import { notFound, redirect } from 'next/navigation';
import { source } from '../../../lib/source';
import { DocsPage, DocsBody, DocsTitle, DocsDescription } from 'fumadocs-ui/page';
import defaultMdxComponents from 'fumadocs-ui/mdx';
import { Steps, Step } from 'fumadocs-ui/components/steps';
import { Tabs, Tab } from 'fumadocs-ui/components/tabs';
import { Callout } from 'fumadocs-ui/components/callout';
import { Card, Cards } from 'fumadocs-ui/components/card';
import { Accordion, Accordions } from 'fumadocs-ui/components/accordion';
import { APIPage } from 'fumadocs-openapi/ui';
import path from 'path';
import type { ReactNode } from 'react';

export const dynamic = 'force-static';

export function generateStaticParams() {
  return source.generateParams();
}

interface Props {
  params: Promise<{ slug?: string[] }>;
}

const mdxComponents = {
  ...defaultMdxComponents,
  Steps,
  Step,
  Tabs,
  Tab,
  Callout,
  Card,
  Cards,
  Accordion,
  Accordions,
};

export default async function Page(props: Props): Promise<ReactNode> {
  const params = await props.params;
  const slug = params.slug ?? [];

  if (slug.length === 0) {
    redirect('/docs/%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B/%E9%9B%86%E6%88%90%E5%B9%B3%E5%8F%B0%E6%A6%82%E8%A7%88');
  }

  const page = source.getPage(slug);
  if (!page) notFound();

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const data = page.data as any;
  const Content = data.body as React.ComponentType<{ components?: Record<string, unknown> }>;

  // API pages generated by fumadocs-openapi have _openapi frontmatter
  const isApiPage = Boolean(data._openapi);

  if (isApiPage) {
    // Resolve openapi.yaml to absolute path (v8 generates relative "openapi.yaml")
    const docPath = path.resolve(process.cwd(), 'openapi.yaml');
    const operations = data._openapi?.operations
      ?? [{ path: data._openapi?.route, method: (data._openapi?.method as string)?.toLowerCase() }];

    return (
      <DocsPage
        toc={data.toc ?? []}
        full={data.full ?? true}
        tableOfContent={{ enabled: false }}
        breadcrumb={{ enabled: true }}
        footer={{ enabled: true }}
      >
        <DocsTitle>{page.data.title}</DocsTitle>
        <DocsDescription>{page.data.description}</DocsDescription>
        <DocsBody>
          <APIPage
            document={docPath}
            operations={operations}
            webhooks={[]}
            hasHead={false}
          />
        </DocsBody>
      </DocsPage>
    );
  }

  return (
    <DocsPage
      toc={data.toc ?? []}
      full={data.full}
      tableOfContent={{ enabled: true, style: 'normal' }}
      breadcrumb={{ enabled: true }}
      footer={{ enabled: true }}
    >
      <DocsTitle>{page.data.title}</DocsTitle>
      <DocsDescription>{page.data.description}</DocsDescription>
      <DocsBody>
        <Content components={mdxComponents} />
      </DocsBody>
    </DocsPage>
  );
}
